### ISSUE TITLE
Store current crafting list in local storage

### ISSUE THREAD

**Issue by kyleshrader** [Last-Oasis-Crafter/lastoasis-crafting-calculator#5]
The current crafting list should not be lost on refresh. Use local storage

**Comment by kyleshrader** [comment]
Should also display "Last saved x minutes ago" and auto save as the crafting object is modified.

**Comment by Elathiel-gh** [comment]
When this feature is implemented we will need a button that removes all recipes from the crafting list or start a new one. Depends on the implementation of #6.

**Comment by kyleshrader** [comment]
I think this will be the first version implemented. That way between page loads and refreshing, it is not lost.

**Comment by Elathiel-gh** [comment]
Sorry @kyleshrader I think my explanation was not clear. I meant that right now i use the refresh to clear the crafting list instead of manually delete each item. When this new feature, of auto-saving the current crafting list, is implemented we will need an alternative option to clear the list. 

That is at least until the other system proposed on #6 is implemented as well, which i guess it would support full CRUD for the crafting lists and not only save/load.

**Comment by kyleshrader** [comment]
Gotcha. A clear all button. That would be pretty straightforward
